#cloud-config
users:
  - name: alejo
    groups: [sudo]
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - SSH_KEY_PLACEHOLDER
package_update: true
package_upgrade: true
packages: [git, tmux, unattended-upgrades, build-essential, curl, jq, sqlite3]
write_files:
  - path: /etc/ssh/sshd_config.d/10-hardening.conf
    content: |
      PermitRootLogin no
      PasswordAuthentication no
runcmd:
  - systemctl restart ssh
